import * as ort from 'onnxruntime-web';
import { CONSTANTS, DemucsProcessor } from 'demucs-web';
import { AudioToMidiError, AudioToMidiConverter, audioToMidiDefaults } from '@musicbento/audio-to-midi';
import './style.css';

const MAX_BYTES=100*1024*1024, MAX_SECONDS=8*60, STEMS=['vocals','bass','other','drums'];
const $=s=>document.querySelector(s), el={file:$('#file-input'),drop:$('#dropzone'),card:$('#file-card'),name:$('#file-name'),meta:$('#file-meta'),audio:$('#audio-player'),go:$('#convert-button'),remove:$('#remove-file'),panel:$('#progress-panel'),bar:$('#progress-bar'),pct:$('#progress-percent'),status:$('#status-text'),result:$('#result-panel'),stats:$('#stats'),download:$('#download-button'),reset:$('#reset-button')};
let file=null,url=null,resultBlob=null,busy=false,separator,separatorReady=false,converter,cpuConverter;
const status=s=>({sep:'音源をボーカル・ベース・その他・ドラムへ分離しています…',decode:'音声を解析用データへ変換しています…',model:'MIDI変換AIモデルを読み込んでいます…',midi:'分離した音源を個別にMIDI化しています…',drum:'ドラム専用解析でキック・スネア・ハイハットを検出しています…',merge:'各ステムのMIDIを統合しています…'})[s]||'解析しています…';
function progress(v,t){v=Math.max(0,Math.min(1,v));el.bar.style.width=`${v*100}%`;el.pct.textContent=`${Math.round(v*100)}%`;if(t)el.status.textContent=t} function err(t){el.status.textContent=t;el.status.classList.add('error-text')} function clearErr(){el.status.classList.remove('error-text')}
function bytes(n){return n<1024?`${n} B`:n<1048576?`${(n/1024).toFixed(1)} KB`:`${(n/1048576).toFixed(1)} MB`} function duration(s){s=Math.round(s);return `${Math.floor(s/60)}:${String(s%60).padStart(2,'0')}`}
async function inspect(f){clearErr();if(!f)return;const ext=f.name.split('.').pop()?.toLowerCase();if(!['mp3','wav','m4a','aac','ogg','flac','webm'].includes(ext))return err('対応形式は MP3 / WAV / M4A / AAC / OGG / FLAC / WebM です。');if(f.size>MAX_BYTES)return err('ファイルは100 MB以下にしてください。');try{const u=URL.createObjectURL(f),a=new Audio();a.preload='metadata';await new Promise((res,rej)=>{a.onloadedmetadata=()=>res();a.onerror=()=>rej(new Error());a.src=u});URL.revokeObjectURL(u);if(a.duration>MAX_SECONDS)return err('音声は8分以内にしてください。');if(url)URL.revokeObjectURL(url);url=URL.createObjectURL(f);file=f;el.name.textContent=f.name;el.meta.textContent=`${bytes(f.size)} · ${duration(a.duration)}`;el.card.classList.remove('hidden');el.audio.src=url;el.audio.classList.remove('hidden');el.go.disabled=false;el.result.classList.add('hidden')}catch{err('この音声をブラウザで読み込めませんでした。')}}
function ios(){return /iPad|iPhone|iPod/.test(navigator.userAgent)||(navigator.platform==='MacIntel'&&navigator.maxTouchPoints>1)}
function getSeparator(){if(separator)return separator;ort.env.wasm.numThreads=1;separator=new DemucsProcessor({ort,sessionOptions:{enableCpuMemArena:false,enableMemPattern:false,executionProviders:ios()?['wasm']:['webgpu','wasm']},onProgress:({progress:p})=>progress(.05+p*.45,status('sep'))});return separator}
async function decode(f){const c=new AudioContext({sampleRate:CONSTANTS.SAMPLE_RATE});try{const b=await c.decodeAudioData((await f.arrayBuffer()).slice(0));if(b.sampleRate!==CONSTANTS.SAMPLE_RATE)throw new Error(`sample-rate-${b.sampleRate}`);const l=new Float32Array(b.length),r=new Float32Array(b.length),a=b.getChannelData(0),d=b.numberOfChannels>1?b.getChannelData(1):a;l.set(a);r.set(d);return{l,r}}finally{await c.close()}}
function wav(stem){const n=Math.min(stem.left.length,stem.right.length),x=new Uint8Array(44+n*4),v=new DataView(x.buffer),w=(o,s)=>[...s].forEach((c,i)=>v.setUint8(o+i,c.charCodeAt(0)));w(0,'RIFF');v.setUint32(4,36+n*4,true);w(8,'WAVE');w(12,'fmt ');v.setUint32(16,16,true);v.setUint16(20,1,true);v.setUint16(22,2,true);v.setUint32(24,44100,true);v.setUint32(28,176400,true);v.setUint16(32,4,true);v.setUint16(34,16,true);w(36,'data');v.setUint32(40,n*4,true);for(let i=0,o=44;i<n;i++,o+=4){const q=z=>Math.round(Math.max(-1,Math.min(1,z))*(z<0?32768:32767));v.setInt16(o,q(stem.left[i]),true);v.setInt16(o+2,q(stem.right[i]),true)}return new File([x],`${stem.name}.wav`,{type:'audio/wav'})}
function rv(b,i){let v=0;for(let n=0;n<4;n++){if(i>=b.length)throw Error('bad-midi');const x=b[i++];v=(v<<7)|(x&127);if(!(x&128))return[v,i]}throw Error('bad-midi')}
function pv(n){let b=n&127,r=[];while(n>>=7){b<<=8;b|=(n&127)|128}for(;;){r.push(b&255);if(b&128)b>>=8;else return r}}
function u32(b,i){return((b[i]<<24)|(b[i+1]<<16)|(b[i+2]<<8)|b[i+3])>>>0}function u16(n){return[(n>>8)&255,n&255]}function u32o(n){return[(n>>>24)&255,(n>>>16)&255,(n>>>8)&255,n&255]}
function parseMidi(b){if(String.fromCharCode(...b.slice(0,4))!=='MThd')throw Error('not-midi');const div=(b[12]<<8)|b[13],count=(b[10]<<8)|b[11];if(div&32768)throw Error('bad-division');let o=8+u32(b,4),tracks=[];for(let ti=0;ti<count;ti++){if(String.fromCharCode(...b.slice(o,o+4))!=='MTrk')throw Error('bad-track');const e=o+8+u32(b,o+4),events=[];let c=o+8,t=0,run=null;while(c<e){let q=rv(b,c);t+=q[0];c=q[1];let s=b[c];if(s<128){if(run===null)throw Error('bad-running');s=run}else{c++;run=s<240?s:null}let d;if(s===255){const type=b[c++],q2=rv(b,c);c=q2[1];d=[type,...b.slice(c,c+q2[0])];c+=q2[0]}else{const n=(s&240)===192||(s&240)===208?1:2;d=[...b.slice(c,c+n)];c+=n}events.push({t,s,d})}tracks.push(events);o=e}return{div,tracks}}
function varEvent(type,data,t=0){return{t,s:255,d:[type,...data]}}function name(n){return varEvent(3,[...new TextEncoder().encode(n)])}function eot(t){return varEvent(47,[],t)}
function encode(tracks,div){const out=[77,84,104,100,0,0,0,6,0,1,...u16(tracks.length),...u16(div)];for(const evs of tracks){let tr=[],p=0;for(const e of evs){tr.push(...pv(Math.max(0,e.t-p)),e.s,...e.d);p=e.t}out.push(77,84,114,107,...u32o(tr.length),...tr)}return new Uint8Array(out)}
function midiTrack(parsed,stem){const ch={vocals:0,bass:1,other:2}[stem],out=[];for(const src of parsed.tracks){const ev=src.filter(e=>e.s>=128&&e.s<=239).map(e=>({...e,s:(e.s&240)|ch}));if(ev.length){const last=ev.at(-1).t;out.push([name(stem),...ev,eot(last)])}}return out.flat()}
function drumMidi(stem,div){const L=stem.left,R=stem.right,n=Math.min(L.length,R.length),hop=512,win=1024,frames=Math.max(1,Math.floor(Math.max(0,n-win)/hop)+1),r=new Float32Array(frames),h=new Float32Array(frames);for(let f=0;f<frames;f++){let e=0,hi=0,prev=0;for(let j=0;j<win;j++){const i=Math.min(n-1,f*hop+j),x=(L[i]+R[i])*.5;e+=x*x;hi+=(x-prev)**2;prev=x}r[f]=Math.sqrt(e/win);h[f]=Math.sqrt(hi/win)}const med=a=>Array.from(a).sort((x,y)=>x-y)[Math.floor(a.length/2)]||0,rf=Math.max(.006,med(r)*1.2),hf=Math.max(.002,med(h)*1.4),ev=[name('drums')];let lk=-1e9,ls=-1e9,lh=-1e9;for(let f=1;f<frames;f++){const t=Math.round(f*hop/44100*div*2),dr=r[f]-r[f-1],dh=h[f]-h[f-1];if(r[f]>rf&&dr>rf*.16&&f*hop-lk>1985){ev.push({t,s:153,d:[36,Math.min(127,Math.round(55+r[f]*700))]},{t:t+1,s:137,d:[36,0]});lk=f*hop}if(h[f]>hf&&dh>hf*.16&&f*hop-ls>2500){ev.push({t,s:153,d:[38,Math.min(127,Math.round(45+h[f]*850))]},{t:t+1,s:137,d:[38,0]});ls=f*hop}if(h[f]>hf*1.05&&dh>hf*.08&&f*hop-lh>2430){ev.push({t,s:153,d:[42,Math.min(110,Math.round(35+h[f]*500))]},{t:t+1,s:137,d:[42,0]});lh=f*hop}}ev.sort((a,b)=>a.t-b.t);ev.push(eot(ev.at(-1).t));return ev}
function getConv(cpu=false){if(cpu&&cpuConverter)return cpuConverter;if(!cpu&&converter)return converter;const o={...audioToMidiDefaults};if(cpu)o.backend='cpu';const c=new AudioToMidiConverter(o);if(cpu)cpuConverter=c;else converter=c;return c}
function gpuFail(e){return /webgl|webgpu|shader|backend|gpu/i.test(String(e?.message||e))}
async function basic(stem,i,total){const base=.55+i/total*.33,onStatus=({status:s})=>progress(base,status(s==='loading-model'?'model':s==='transcribing'?'midi':s)),onProgress=({progress:p})=>progress(base+p/total*.33,status('midi'));try{return await getConv().convert(wav(stem),{onStatus,onProgress})}catch(e){if(!gpuFail(e))throw e;return getConv(true).convert(wav(stem),{onStatus,onProgress})}}
async function convertAll(){if(!file||busy)return;busy=true;el.go.disabled=true;el.panel.classList.remove('hidden');el.result.classList.add('hidden');clearErr();try{progress(.02,status('model'));const p=getSeparator();if(!separatorReady){await p.loadModel(CONSTANTS.DEFAULT_MODEL_URL);separatorReady=true}progress(.05,status('decode'));const a=await decode(file),s=await p.separate(a.l,a.r),tracks=[],non=STEMS.filter(x=>x!=='drums'&&s[x]?.left?.length);let div=480;for(let i=0;i<non.length;i++){const x=non[i],m=await basic({name:x,...s[x]},i,non.length);const q=parseMidi(new Uint8Array(await m.midiBlob.arrayBuffer()));div=q.div;tracks.push(...midiTrack(q,x))}if(s.drums?.left?.length){progress(.9,status('drum'));tracks.push(drumMidi(s.drums,div))}if(!tracks.length)throw Error('no-midi-tracks');progress(.96,status('merge'));resultBlob=new Blob([encode([[name('Conductor'),eot(div)],...tracks],div)],{type:'audio/midi'});el.stats.textContent=`${non.length+(s.drums?1:0)}ステムを分離 → 個別MIDI化 → 統合 · ${bytes(resultBlob.size)}`;el.result.classList.remove('hidden');progress(1,'変換が完了しました。')}catch(e){console.error(e);err(`変換に失敗しました。${e instanceof AudioToMidiError?e.message:e?.message||e}`)}finally{busy=false;el.go.disabled=!file}}
function reset(){if(busy)return;file=null;resultBlob=null;el.file.value='';el.card.classList.add('hidden');el.audio.classList.add('hidden');el.audio.removeAttribute('src');el.go.disabled=true;el.panel.classList.add('hidden');el.result.classList.add('hidden');clearErr();progress(0,'準備しています…');if(url){URL.revokeObjectURL(url);url=null}}
el.go.onclick=convertAll;el.remove.onclick=reset;el.reset.onclick=reset;el.download.onclick=()=>{if(!resultBlob)return;const u=URL.createObjectURL(resultBlob),a=document.createElement('a');a.href=u;a.download=`${file?.name.replace(/\.[^.]+$/,'')||'converted'}-separated.mid`;a.click();setTimeout(()=>URL.revokeObjectURL(u),0)};el.file.onchange=e=>inspect(e.target.files?.[0]);el.drop.ondragover=e=>{e.preventDefault();el.drop.classList.add('dragover')};el.drop.ondragleave=()=>el.drop.classList.remove('dragover');el.drop.ondrop=e=>{e.preventDefault();el.drop.classList.remove('dragover');inspect(e.dataTransfer.files?.[0])};